### ISSUE TITLE
is Something wrong with pod installation 

### ISSUE THREAD

**Issue by A-jay98** [SagarSDagdu/SDDownloadManager#1]
when i try to add this to my project using pods , after importing the model in my code , the only property SDDownloadManager has is version number , and i can't use any of functions

**Comment by SagarSDagdu** [comment]
@A-jay98 Hey, it was a issue from my end, I've fixed it. Please update your pod. Sorry for the inconvenience

**Comment by SagarSDagdu** [comment]
Fixed in 1.0.2
