### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by tooolbox** [SagarSDagdu/SDDownloadManager#12]
Great that you have CocoaPods support, what about Carthage?  😄 

https://medium.com/@filippotosetto/how-to-create-a-carthage-framework-8d9d65f98ac2

**Comment by SagarSDagdu** [comment]
Planning very soon, thanks for the resource 👍🏻

**Comment by SagarSDagdu** [comment]
> Great that you have CocoaPods support, what about Carthage? 😄
> 
> https://medium.com/@filippotosetto/how-to-create-a-carthage-framework-8d9d65f98ac2

Planning very soon, thanks for the resource 👍🏻

**Comment by SagarSDagdu** [comment]
I do not have carthage support planned as of now, feel free to raise a PR for it if needed.
