### ISSUE TITLE
how to change download path to download files in documents ?

### ISSUE THREAD

**Issue by A-jay98** [SagarSDagdu/SDDownloadManager#2]
i need the files to be download in documents folder should i move it after i download them or is there method in it ?, also is there way of getting speed ratio that would be great thanks 😀

**Comment by SagarSDagdu** [comment]
1)As explained in Readme file, the default path is inside caches directory.( and this is preferable)  If you want the file at some other location, you can move it as you get the URL in completion block. 
2)Can you elaborate on this? May be support it with a use case.

**Comment by A-jay98** [comment]
is there a way to get download speed for a specific task , or get the speed for all the tasks combined , get remaining time or file size ? these would be great features to add 
PS: 👍  for your project , it's updated , clean and easy to use

**Comment by SagarSDagdu** [comment]
@A-jay98 Remaining time / Remaining file size entirely depends on how the network behaves at that point of time. I don't think so that responsibility lies with the Download Manager, hence haven't included them. Maybe you can fork and add these for your use. Thanks!
