### ISSUE TITLE
Multiple Downloads synchronously

### ISSUE THREAD

**Issue by Jigneshiosdeveloper** [SagarSDagdu/SDDownloadManager#5]
Hi... Thanks for great work. 

- Can you please update this library with Multiple Downloads synchronously.
- Can you add pause the downloading & start at that point.
- Can you please provide total size & remaining downloads size.

Thanks.

**Comment by SagarSDagdu** [comment]
Hi, 
Synchronously means, you want to download the next file on completion of the previous one?

**Comment by Jigneshiosdeveloper** [comment]
Hi,
    Thanks for reply. I want to download multiple files parallel means if one file is downloading at that time second file wants to download(so both files downloading at same time). but here second file will start download on the completion of the first one. 
i also want pause & resume for each file download. please update it as soon as possible.

**Comment by SagarSDagdu** [comment]
Multiple downloads are possible with existing code. Just call the `downloadFile()` for each download you want to start. Pause and resume will be supported in future releases, meanwhile you can start working on it raise a PR. I would be more than happy to merge it.
