### ISSUE TITLE
Function misspelled, dowloadFile -> downloadFile

### ISSUE THREAD

**Issue by Joohansson** [SagarSDagdu/SDDownloadManager#6]
Should be "downloadFile".

Also, maybe improve the README how to actually use the library. I took me a while to figure out that the singleton functions is called like SDDownloadManager.shared.dowloadFile and not from SDDownloadManager.downloadFile. Never used singleton before. Also in xcode after you installed the pod (and add the line "import SDDownloadManager") you need to build your project before you can access the class at all. Small details for newbies like me. Also I think the instructions for the pod is wrong, I had to write it like this:

```
platform :ios, '11.4'
target "Download_Test" do
  pod 'SDDownloadManager'
end
```

**Comment by SagarSDagdu** [comment]
I have updated the function name.
